apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: academy-ingress-cert
spec:
  secretName: academy-ingress-secret
  issuerRef:
    name: letsencrypt-prod-my-academy
    kind: ClusterIssuer
  dnsNames:
    - drive.myjiujitsuacademy.com
    - login.myjiujitsuacademy.com
    - myjiujitsuacademy.com
